version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm i @angular-devkit/build-angular@0.803.24
            - run: npm install
            - run: npm update 
            - run: npm upgrade 
workflows:
    build-and-test:
      jobs:
        